export const subjects = [
  "Начальная школа — Primary Teacher, Homeroom Teacher, Elementary Teacher",
  "Дошкольное образование — Early Years, Nursery, Kindergarten Teacher",
  "Английский язык и литература — English Language, English Literature, EAL",
  "Математика — Mathematics Teacher",
  "Физика — Physics Teacher",
  "Химия — Chemistry Teacher",
  "Биология — Biology Teacher",
  "Естественные науки — General / Integrated Science",
  "Информатика — Computer Science, ICT, Computing",
  "Бизнес и экономика — Business Studies, Economics",
  "История — History Teacher",
  "География — Geography Teacher",
  "Обществознание — Social Studies, Social Sciences",
  "Гуманитарные науки — Humanities",
  "Музыка — Music Teacher, Instrumental Music",
  "Изобразительное искусство — Art & Design",
  "Драма и театр — Drama, Theatre",
  "Физическая культура — PE / Physical Education",
  "Современные языки — French, Spanish, German, Mandarin и др.",
  "Design Technology — Design, Technology, Engineering",
  "Психология — Psychology",
  "Learning Support / SEN — поддержка учащихся и специальное образование",
  "Библиотека — Librarian / Teacher Librarian",
  "College / University Counselling — профориентация и поступление в университет",
  "Узбекский язык — Uzbek",
  "Русский язык — Russian",
  "Казахский язык — Kazakh",
  "Таджикский язык — Tajik",
  "Туркменский язык — Turkmen",
  "Кыргызский язык — Kyrgyz",
];
